version: "3.8"

services:
  # Servicio que ejecuta la aplicación web
  calculadora-app:

    # Imagen publicada en DockerHub mediante GitHub Actions
    image: pabloagustinm/calculadora:uploadAuto

    # Mapeo de puertos:
    ports:
      - "8080:80"

    # Healthcheck para verificar que la aplicación esté disponible
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
