apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculadora-deployment
spec:
  # Cantidad de r√©plicas del contenedor
  replicas: 2

  selector:
    matchLabels:
      app: calculadora

  template:
    metadata:
      labels:
        app: calculadora
    spec:
      containers:
        - name: calculadora
          # Imagen a subir con GitHub Actions
          image: pabloagustinm/calculadora:uploadAuto

          # Puerto interno del contenedor
          ports:
            - containerPort: 80
